### ISSUE TITLE
Bad console output crashes newlogd and causes an EVE reboot

### ISSUE THREAD

**Issue by DolceTriade** [lf-edge/eve#3090]
Please provide information requested in the template below as much as possible.

#### Describe the bug

If your workload prints bad output to the console (which EVE logs), it can cause a crash.

#### Recent release

Yes. tested on custom image close to 9.6.0 (but no modifications to the pillar code)

#### Duplicate

Don't think so...
#### How to reproduce

* EVE-OS version [9.6.0]
* EVE-OS hardware architecture [amd64]

Print to serial console (or just run from serial console)
```shell
cat <<EOF
{"time": "2023-03-08 20:10:02.871589", "state": "Initialization", "details": "User-data verification successful", "status": true}
{"time": "2023-03-08 20:10:02.873839", "state": "SSH-Keys Addition", "details": "Add Success", "status": true}
{"time": "2023-03-08 20:10:02.923809", "state": "Initialization", "details": "Deleted cron entry", "status": true}
EOF
```

#### Expected behavior

Machine doesn't reboot regardless of what's printed on the console

#### Error message

```
839cad56-d77b-4ec1-89b0-6a61d2a6a8ec:/persist/log# cat reboot-reason.log
Reboot from agent newlogd[2129] in partition IMGA at EVE version 0.0.0-main-72c0455f-dirty-2023-02-22.00.33-kvm-amd64 at 2023-03-08T05:43:16.503877594Z: fatal: agent newlogd[2129]: parsing time "2023-03-08 05:14:02.387748" as "2006-01-02T15:04:05Z07:00": cannot parse " 05:14:02.387748" as "T"
Reboot from agent newlogd[15034] in partition IMGA at EVE version 0.0.0-main-72c0455f-dirty-2023-02-22.00.33-kvm-amd64 at 2023-03-08T05:44:07.183525716Z: fatal: agent newlogd[15034]: parsing time "2023-03-08 05:14:02.387748" as "2006-01-02T15:04:05Z07:00": cannot parse " 05:14:02.387748" as "T"
Reboot from agent newlogd[2129] in partition IMGA at EVE version 0.0.0-main-72c0455f-dirty-2023-02-22.00.33-kvm-amd64 at 2023-03-08T10:10:04.944389539Z: fatal: agent newlogd[2129]: parsing time "2023-03-08 10:10:03.146881" as "2006-01-02T15:04:05Z07:00": cannot parse " 10:10:03.146881" as "T"
Reboot from agent newlogd[22293] in partition IMGA at EVE version 0.0.0-main-72c0455f-dirty-2023-02-22.00.33-kvm-amd64 at 2023-03-08T10:11:06.06154024Z: fatal: agent newlogd[22293]: parsing time "2023-03-08 10:10:03.146881" as "2006-01-02T15:04:05Z07:00": cannot parse " 10:10:03.146881" as "T"
Reboot from agent newlogd[2126] in partition IMGA at EVE version 0.0.0-main-72c0455f-dirty-2023-02-22.00.33-kvm-amd64 at 2023-03-08T10:32:29.204976565Z: fatal: agent newlogd[2126]: parsing time "2023-03-08 10:10:03.146881" as "2006-01-02T15:04:05Z07:00": cannot parse " 10:10:03.146881" as "T"
Reboot from agent newlogd[28425] in partition IMGA at EVE version 0.0.0-main-72c0455f-dirty-2023-02-22.00.33-kvm-amd64 at 2023-03-08T10:33:26.158020335Z: fatal: agent newlogd[28425]: parsing time "2023-03-08 10:10:03.146881" as "2006-01-02T15:04:05Z07:00": cannot parse " 10:10:03.146881" as "T"
Reboot from agent newlogd[2160] in partition IMGA at EVE version 0.0.0-main-72c0455f-dirty-2023-02-22.00.33-kvm-amd64 at 2023-03-08T10:39:52.686767262Z: fatal: agent newlogd[2160]: parsing time "2023-03-08 10:10:03.146881" as "2006-01-02T15:04:05Z07:00": cannot parse " 10:10:03.146881" as "T"
Reboot from agent newlogd[10992] in partition IMGA at EVE version 0.0.0-main-72c0455f-dirty-2023-02-22.00.33-kvm-amd64 at 2023-03-08T10:40:34.989034513Z: fatal: agent newlogd[10992]: parsing time "2023-03-08 10:10:03.146881" as "2006-01-02T15:04:05Z07:00": cannot parse " 10:10:03.146881" as "T"
Reboot from agent newlogd[2160] in partition IMGA at EVE version 0.0.0-main-72c0455f-dirty-2023-02-22.00.33-kvm-amd64 at 2023-03-08T20:28:15.14649623Z: fatal: agent newlogd[2160]: parsing time "2023-03-08 20:10:02.871589" as "2006-01-02T15:04:05Z07:00": cannot parse " 20:10:02.871589" as "T"
Reboot from agent newlogd[23932] in partition IMGA at EVE version 0.0.0-main-72c0455f-dirty-2023-02-22.00.33-kvm-amd64 at 2023-03-08T20:29:09.30643989Z: fatal: agent newlogd[23932]: parsing time "2023-03-08 20:10:02.871589" as "2006-01-02T15:04:05Z07:00": cannot parse " 20:10:02.871589" as "T"
```

```
839cad56-d77b-4ec1-89b0-6a61d2a6a8ec:/persist/log# cat reboot-stack.log
goroutine 9 [running]:
github.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0x80?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:471 +0x5c
github.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc0000aa480?, {0x7de711, 0x7}, 0x0?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:242 +0x4a
github.com/lf-edge/eve/pkg/pillar/agentlog.initImpl.func1()
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:653 +0x29
github.com/sirupsen/logrus.runHandler(0x6382cf?)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x3e
github.com/sirupsen/logrus.runHandlers(...)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:44
github.com/sirupsen/logrus.(*Logger).Exit(0xc00009cd90, 0x1?)
	/newlog/vendor/github.com/sirupsen/logrus/logger.go:337 +0x4c
github.com/sirupsen/logrus.(*Entry).Fatal(0xc0001fc230, {0xc00006dbc8?, 0xc000481050?, 0x21?})
	/newlog/vendor/github.com/sirupsen/logrus/entry.go:327 +0x45
github.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatal(0x7e6804?, {0xc00006dbc8, 0x1, 0x1})
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/base/log.go:70 +0x59
main.getPtypeTimestamp({0xc000497dc0?, 0x24?})
	/newlog/cmd/newlogd.go:1581 +0x96
main.writelogFile(0xc00005a600, 0x0?)
	/newlog/cmd/newlogd.go:765 +0x4d1
created by main.main
	/newlog/cmd/newlogd.go:187 +0x3ae

goroutine 9 [running]:
github.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0x80?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:471 +0x5c
github.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc0001cfe60?, {0x7de711, 0x7}, 0x0?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:242 +0x4a
github.com/lf-edge/eve/pkg/pillar/agentlog.initImpl.func1()
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:653 +0x29
github.com/sirupsen/logrus.runHandler(0x6382cf?)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x3e
github.com/sirupsen/logrus.runHandlers(...)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:44
github.com/sirupsen/logrus.(*Logger).Exit(0xc000094d90, 0x1?)
	/newlog/vendor/github.com/sirupsen/logrus/logger.go:337 +0x4c
github.com/sirupsen/logrus.(*Entry).Fatal(0xc0003a2ee0, {0xc000065bc8?, 0xc000077d70?, 0x21?})
	/newlog/vendor/github.com/sirupsen/logrus/entry.go:327 +0x45
github.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatal(0x7e6804?, {0xc000065bc8, 0x1, 0x1})
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/base/log.go:70 +0x59
main.getPtypeTimestamp({0xc00037c7c0?, 0x24?})
	/newlog/cmd/newlogd.go:1581 +0x96
main.writelogFile(0xc0000525a0, 0x0?)
	/newlog/cmd/newlogd.go:765 +0x4d1
created by main.main
	/newlog/cmd/newlogd.go:187 +0x3ae

goroutine 9 [running]:
github.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0x80?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:471 +0x5c
github.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc000366120?, {0x7de711, 0x7}, 0x0?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:242 +0x4a
github.com/lf-edge/eve/pkg/pillar/agentlog.initImpl.func1()
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:653 +0x29
github.com/sirupsen/logrus.runHandler(0x6382cf?)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x3e
github.com/sirupsen/logrus.runHandlers(...)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:44
github.com/sirupsen/logrus.(*Logger).Exit(0xc00009cd90, 0x1?)
	/newlog/vendor/github.com/sirupsen/logrus/logger.go:337 +0x4c
github.com/sirupsen/logrus.(*Entry).Fatal(0xc00036b260, {0xc00033dbc8?, 0xc00007e9f0?, 0x21?})
	/newlog/vendor/github.com/sirupsen/logrus/entry.go:327 +0x45
github.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatal(0x7e6804?, {0xc00033dbc8, 0x1, 0x1})
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/base/log.go:70 +0x59
main.getPtypeTimestamp({0xc000334800?, 0x24?})
	/newlog/cmd/newlogd.go:1581 +0x96
main.writelogFile(0xc00005a600, 0x0?)
	/newlog/cmd/newlogd.go:765 +0x4d1
created by main.main
	/newlog/cmd/newlogd.go:187 +0x3ae

goroutine 9 [running]:
github.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0x80?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:471 +0x5c
github.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc000210000?, {0x7de711, 0x7}, 0x0?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:242 +0x4a
github.com/lf-edge/eve/pkg/pillar/agentlog.initImpl.func1()
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:653 +0x29
github.com/sirupsen/logrus.runHandler(0x6382cf?)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x3e
github.com/sirupsen/logrus.runHandlers(...)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:44
github.com/sirupsen/logrus.(*Logger).Exit(0xc00009cd90, 0x1?)
	/newlog/vendor/github.com/sirupsen/logrus/logger.go:337 +0x4c
github.com/sirupsen/logrus.(*Entry).Fatal(0xc000323dc0, {0xc00006dbc8?, 0xc0004ca420?, 0x21?})
	/newlog/vendor/github.com/sirupsen/logrus/entry.go:327 +0x45
github.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatal(0x7e6804?, {0xc00006dbc8, 0x1, 0x1})
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/base/log.go:70 +0x59
main.getPtypeTimestamp({0xc0002f0340?, 0x24?})
	/newlog/cmd/newlogd.go:1581 +0x96
main.writelogFile(0xc0000525a0, 0x0?)
	/newlog/cmd/newlogd.go:765 +0x4d1
created by main.main
	/newlog/cmd/newlogd.go:187 +0x3ae

goroutine 9 [running]:
github.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0x80?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:471 +0x5c
github.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc00032afc0?, {0x7de711, 0x7}, 0x0?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:242 +0x4a
github.com/lf-edge/eve/pkg/pillar/agentlog.initImpl.func1()
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:653 +0x29
github.com/sirupsen/logrus.runHandler(0x6382cf?)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x3e
github.com/sirupsen/logrus.runHandlers(...)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:44
github.com/sirupsen/logrus.(*Logger).Exit(0xc000094d90, 0x1?)
	/newlog/vendor/github.com/sirupsen/logrus/logger.go:337 +0x4c
github.com/sirupsen/logrus.(*Entry).Fatal(0xc000399f80, {0xc000065bc8?, 0xc000478990?, 0x21?})
	/newlog/vendor/github.com/sirupsen/logrus/entry.go:327 +0x45
github.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatal(0x7e6804?, {0xc000065bc8, 0x1, 0x1})
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/base/log.go:70 +0x59
main.getPtypeTimestamp({0xc000499d80?, 0x24?})
	/newlog/cmd/newlogd.go:1581 +0x96
main.writelogFile(0xc00005a600, 0x0?)
	/newlog/cmd/newlogd.go:765 +0x4d1
created by main.main
	/newlog/cmd/newlogd.go:187 +0x3ae

goroutine 9 [running]:
github.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0x80?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:471 +0x5c
github.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc0002c6360?, {0x7de711, 0x7}, 0x0?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:242 +0x4a
github.com/lf-edge/eve/pkg/pillar/agentlog.initImpl.func1()
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:653 +0x29
github.com/sirupsen/logrus.runHandler(0x6382cf?)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x3e
github.com/sirupsen/logrus.runHandlers(...)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:44
github.com/sirupsen/logrus.(*Logger).Exit(0xc00009cd90, 0x1?)
	/newlog/vendor/github.com/sirupsen/logrus/logger.go:337 +0x4c
github.com/sirupsen/logrus.(*Entry).Fatal(0xc000167030, {0xc00006dbc8?, 0xc00007f650?, 0x21?})
	/newlog/vendor/github.com/sirupsen/logrus/entry.go:327 +0x45
github.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatal(0x7e6804?, {0xc00006dbc8, 0x1, 0x1})
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/base/log.go:70 +0x59
main.getPtypeTimestamp({0xc00046f200?, 0x24?})
	/newlog/cmd/newlogd.go:1581 +0x96
main.writelogFile(0xc0000525a0, 0x0?)
	/newlog/cmd/newlogd.go:765 +0x4d1
created by main.main
	/newlog/cmd/newlogd.go:187 +0x3ae

goroutine 9 [running]:
github.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0x80?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:471 +0x5c
github.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc0002c0480?, {0x7de711, 0x7}, 0x0?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:242 +0x4a
github.com/lf-edge/eve/pkg/pillar/agentlog.initImpl.func1()
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:653 +0x29
github.com/sirupsen/logrus.runHandler(0x6382cf?)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x3e
github.com/sirupsen/logrus.runHandlers(...)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:44
github.com/sirupsen/logrus.(*Logger).Exit(0xc000094d90, 0x1?)
	/newlog/vendor/github.com/sirupsen/logrus/logger.go:337 +0x4c
github.com/sirupsen/logrus.(*Entry).Fatal(0xc0002c4d90, {0xc000065bc8?, 0xc0003f55f0?, 0x21?})
	/newlog/vendor/github.com/sirupsen/logrus/entry.go:327 +0x45
github.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatal(0x7e6804?, {0xc000065bc8, 0x1, 0x1})
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/base/log.go:70 +0x59
main.getPtypeTimestamp({0xc00049a0e0?, 0x24?})
	/newlog/cmd/newlogd.go:1581 +0x96
main.writelogFile(0xc00005a600, 0x0?)
	/newlog/cmd/newlogd.go:765 +0x4d1
created by main.main
	/newlog/cmd/newlogd.go:187 +0x3ae

goroutine 9 [running]:
github.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0x80?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:471 +0x5c
github.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc0003cc120?, {0x7de711, 0x7}, 0x0?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:242 +0x4a
github.com/lf-edge/eve/pkg/pillar/agentlog.initImpl.func1()
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:653 +0x29
github.com/sirupsen/logrus.runHandler(0x6382cf?)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x3e
github.com/sirupsen/logrus.runHandlers(...)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:44
github.com/sirupsen/logrus.(*Logger).Exit(0xc00009cd90, 0x1?)
	/newlog/vendor/github.com/sirupsen/logrus/logger.go:337 +0x4c
github.com/sirupsen/logrus.(*Entry).Fatal(0xc0002e8000, {0xc00006dbc8?, 0xc00007fce0?, 0x21?})
	/newlog/vendor/github.com/sirupsen/logrus/entry.go:327 +0x45
github.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatal(0x7e6804?, {0xc00006dbc8, 0x1, 0x1})
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/base/log.go:70 +0x59
main.getPtypeTimestamp({0xc00009ba80?, 0x24?})
	/newlog/cmd/newlogd.go:1581 +0x96
main.writelogFile(0xc0000525a0, 0x0?)
	/newlog/cmd/newlogd.go:765 +0x4d1
created by main.main
	/newlog/cmd/newlogd.go:187 +0x3ae

goroutine 9 [running]:
github.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0x80?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:471 +0x5c
github.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc0000ac900?, {0x7de711, 0x7}, 0x0?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:242 +0x4a
github.com/lf-edge/eve/pkg/pillar/agentlog.initImpl.func1()
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:653 +0x29
github.com/sirupsen/logrus.runHandler(0x6382cf?)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x3e
github.com/sirupsen/logrus.runHandlers(...)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:44
github.com/sirupsen/logrus.(*Logger).Exit(0xc00009ed90, 0x1?)
	/newlog/vendor/github.com/sirupsen/logrus/logger.go:337 +0x4c
github.com/sirupsen/logrus.(*Entry).Fatal(0xc00027bc00, {0xc0004a1bc8?, 0x0?, 0x0?})
	/newlog/vendor/github.com/sirupsen/logrus/entry.go:327 +0x45
github.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatal(0x7e6804?, {0xc0004a1bc8, 0x1, 0x1})
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/base/log.go:70 +0x59
main.getPtypeTimestamp({0xc000498800?, 0x24?})
	/newlog/cmd/newlogd.go:1581 +0x96
main.writelogFile(0xc00005a600, 0x0?)
	/newlog/cmd/newlogd.go:765 +0x4d1
created by main.main
	/newlog/cmd/newlogd.go:187 +0x3ae

goroutine 9 [running]:
github.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0x80?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:471 +0x5c
github.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc00049a900?, {0x7de711, 0x7}, 0x0?)
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:242 +0x4a
github.com/lf-edge/eve/pkg/pillar/agentlog.initImpl.func1()
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/agentlog/agentlog.go:653 +0x29
github.com/sirupsen/logrus.runHandler(0x6382cf?)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x3e
github.com/sirupsen/logrus.runHandlers(...)
	/newlog/vendor/github.com/sirupsen/logrus/alt_exit.go:44
github.com/sirupsen/logrus.(*Logger).Exit(0xc00009cd90, 0x1?)
	/newlog/vendor/github.com/sirupsen/logrus/logger.go:337 +0x4c
github.com/sirupsen/logrus.(*Entry).Fatal(0xc000346a80, {0xc00006dbc8?, 0xc00007e480?, 0x21?})
	/newlog/vendor/github.com/sirupsen/logrus/entry.go:327 +0x45
github.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatal(0x7e6804?, {0xc00006dbc8, 0x1, 0x1})
	/newlog/vendor/github.com/lf-edge/eve/pkg/pillar/base/log.go:70 +0x59
main.getPtypeTimestamp({0xc00009bb00?, 0x24?})
	/newlog/cmd/newlogd.go:1581 +0x96
main.writelogFile(0xc0000525a0, 0x0?)
	/newlog/cmd/newlogd.go:765 +0x4d1
created by main.main
	/newlog/cmd/newlogd.go:187 +0x3ae

```

#### Additional context

None

**Comment by DolceTriade** [comment]
However, the failure to parse the time is a result of the timestamp printed on the screen, not due to the image version? Even so, this shouldn't cause a crash in the first place right?

I'll try to validate with a "clean" image though.

**Comment by uncleDecart** [comment]
Most likely it should solve the problem using clean image name on both cloud and device side

**Comment by DolceTriade** [comment]
Reproduced with a clean image name:
```
Rebooting EVE. Reason: Reboot from agent newlogd[2166] in partition IMGA at EVE version 2023.10.0-kvm-amd64 at 2023-03-09T07:24:12.976548156Z: fatal: agent newlogd[2166]: parsing time "2023-03-08 20:10:02.923809" as "2006-01-02T15:04:05Z07:00": cannot parse " 20:10:02.923809" as "T"
```

I'll try to repro on the official image too...

**Comment by rouming** [comment]
@DolceTriade newlogd.go:1581 could not parse the date (not in the RFC3339 format) and panics. This is the default EVE behavior. Before fixing that, may I ask you what is the source of these log messages? For example this one "Deleted cron ?entry" ?

**Comment by rene** [comment]
This issue is fixed by the PR https://github.com/lf-edge/eve/pull/3099, which is now merged.
